config/routes.rb
Rails.application.routes.draw do
  

  resources :contrato_niveis
  resources :materias
  resources :niveis
  resources :atividade_complementares
  resources :formacoes
  resources :coordenacao_pedagogicas
  resources :planejamento_pedagogicos
  resources :capitulos
  resources :livros
  resources :disciplinas
  resources :series
  resources :niveis
  resources :prefeituras
  resources :cidades
  resources :estados
  resources :ano_letivos
  devise_for :users

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user  do
    
    get  'users/new' => 'users#new'
    post 'users/create' => 'users#create'
    patch 'users/update' => 'users#update'
  end

  root 'home#index'

  get 'docs/docs_buildnotes'
  get 'intel/intel_introduction'
  get 'intel/intel_marketing_dashboard'
  get 'page/page_inbox_general'
  get 'page/page_search'
  get 'utilities/utilities_responsive_grid'

  resources :contratos do
    resources :contrato_niveis
  end

  

  resources :coordenadores do
    collection do
      get 'consulta/:serie_id/:livro_id', to: 'coordenadores#consulta', as: 'consulta'
    end
  end

end

app/models/livro.rb
class Livro < ApplicationRecord
  belongs_to :serie

  has_many :capitulos
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: [:show, :edit, :update, :destroy]

  # GET /livros
  def index
    # @search = Livro.search(params[:q])
    # @livros = @search.result
    authorize Serie
    @livros = Livro.all
  end

  # GET /livros/1
  def show
    authorize Serie
  end

  # GET /livros/new
  def new
    authorize Serie
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
    authorize Serie
  end

  # POST /livros
  def create
    @livro = Livro.new(livro_params)

    if @livro.save
      redirect_to @livro, notice: 'Registro criado com sucesso.'
    else
      render :new
    end
  end

  # PATCH/PUT /livros/1
  def update
    if @livro.update(livro_params)
      redirect_to @livro, notice: 'Registro atualizado com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /livros/1
  def destroy
    if @livro.capitulos.exists? 
      redirect_to livros_url,  alert:"Existe capitulo associado ao livro #{@livro.nome}. Exclusão não permitida."
    else
      @livro.destroy
      redirect_to livros_url, notice: 'Registro removido com sucesso.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def livro_params
      params.require(:livro).permit(:nome, :serie_id, :volume, :ano_edicao)
    end
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/views/livros/_form.html.erb
<div class="row">
  <div class="col-xl-12">
		<div id="panel-1" class="panel">
       <div class="panel-hdr">
         <h2>
          <span class="fw-500">Formulário</span>
				 </h2>
          <div class="panel-toolbar">
              <button class="btn btn-panel waves-effect waves-themed" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
              <button class="btn btn-panel waves-effect waves-themed" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
              <button class="btn btn-panel waves-effect waves-themed" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
          </div>
       </div>
		 	<div class="panel-container show">
				<div class="panel-content"> 
          <%= simple_form_for(@livro) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-inputs">
              <%= f.input :nome %>
              <%= f.association :serie, label_method: :nome, label:"#{Livro.human_attribute_name(:serie_id)}", include_blank: "Por favor, selecione" %>
              <%#= f.association :serie, collection: Serie.all.limit(50), label_method: :nome %>
              <%= f.input :volume %>
              <%#= f.input :ano_edicao %>
          </div>

          <br>

         <button type="submit" class="btn btn-default waves-effect waves-themed">Salvar</button>
         <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
      

app/views/livros/edit.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
 <% content_for(:title, "#{@livro.model_name.human}") %>
    <% content_for(:category_1, 'Cadastros') %>

    <% content_for :heading do %>
      <i class='subheader-icon fal fa-table'></i> <%= @livro.model_name.human %>/Editar
    <% end %> 
  <%= render 'form', livro: @livro %>
</div>

app/views/livros/index.html.erb
<%- model_class = Livro -%>
<div class="row">
	<div class="col-xl-12">
		<div id="panel-1" class="panel">
      <div class="panel-hdr">
        <h2>
          <span class="fw-500"><%= @livros.model_name.human %></span>
				</h2>
        <div class="panel-toolbar">
          <%= link_to "#{content_tag(:i, nil, class: '')} NOVO"
          .html_safe, new_livro_path, class: 'btn btn-primary btn-sm' %>
        </div>
      </div>
			<div class="panel-container show">
				<div class="panel-content">
					<!-- datatable start -->
					<table id="dt-basic-example" class="table table-bordered table-hover table-striped w-100">
						<thead>
							<tr>
								<th width=10></th>
								<th width=10></th>
								<th width=10></th>
                <th><%= model_class.human_attribute_name( :nome) %></th>
                <th><%= model_class.human_attribute_name( :serie_id) %></th>
                <th><%= model_class.human_attribute_name( :volume) %></th>
               <!-- <th><%= model_class.human_attribute_name( :ano_edicao) %></th> -->
             </tr>
						</thead>
            <tbody>
              <% @livros.each do |livro| %>
                <tr>
                  <td class="text-center">
                    <%= link_to content_tag(:i, nil, class: 'ni ni-magnifier' ), livro,
                    class: 'rounded-top d-flex align-items-center justify-content-center w-100 pt-1 pb-1 pr-1 pl-1 fa-1x' , title: 'Visualizar' %>
                  </td>
                  <td class="text-center">
                    <%= link_to content_tag(:i, nil, class: 'ni ni-note' ),
                    edit_livro_path(livro),
                    class: 'rounded-top d-flex align-items-center justify-content-center w-1 pt-1 pb-1 pr-1 pl-1 fa-1x' , title: 'Editar' %>
                  </td>
                  <td class="text-center">
                    <%= link_to content_tag(:i, nil, class: 'ni ni-trash' ), livro, method:
                    :delete, data: { confirm: 'Confirma exclusão?' }, class: 'rounded-top d-flex align-items-center justify-content-center w-1 pt- pb-1 pr-1 pl-1 fa-1x' ,
                    title: 'Remover' %>
                  </td>
                    <td><%= livro.nome %></td>
                    <td><%= livro.serie.nome %></td>
                    <td><%= livro.volume %></td>
                    <!-- <td><%= livro.ano_edicao %></td> -->
                  </tr>
              <% end %>
            </tbody>
						
					</table>
					<!-- datatable end -->
				</div>
			</div>
		</div>
	</div>
</div>

<% content_for :scripts_block do %>
  <!-- datatble responsive bundle contains:
    + jquery.dataTables.js
    + dataTables.bootstrap4.js
    + dataTables.autofill.js
    + dataTables.buttons.js
    + buttons.bootstrap4.js
    + buttons.html5.js
    + buttons.print.js
    + buttons.colVis.js
    + dataTables.colreorder.js
    + dataTables.fixedcolumns.js
    + dataTables.fixedheader.js
    + dataTables.keytable.js
    + dataTables.responsive.js
    + dataTables.rowgroup.js
    + dataTables.rowreorder.js
    + dataTables.scroller.js
    + dataTables.select.js
    + datatables.styles.app.js
    + datatables.styles.buttons.app.js -->
  <%= javascript_include_tag 'smartadmin/datagrid/datatables/datatables.bundle' %>
  <script>

    /* demo scripts for change table color */
    /* change background */


    $(document).ready( function () {
      $('#dt-basic-example').dataTable({
        responsive: true,
        "language": {
          "url": "//cdn.datatables.net/plug-ins/1.11.5/i18n/pt-BR.json"
        }
      });

      $('.js-thead-colors a').on('click', function(){
        var theadColor = $(this).attr("data-bg");
        console.log(theadColor);
        $('#dt-basic-example thead').removeClassPrefix('bg-').addClass(theadColor);
      });

      $('.js-tbody-colors a').on('click', function(){
        var theadColor = $(this).attr("data-bg");
        console.log(theadColor);
        $('#dt-basic-example').removeClassPrefix('bg-').addClass(theadColor);
      });

    });
  </script>
<% end %>

app/views/livros/new.html.erb
  <div class="wrapper wrapper-content animated fadeInRight">
   <% content_for(:title, "#{@livro.model_name.human}") %>
    <% content_for(:category_1, 'Cadastros') %>

    <% content_for :heading do %>
      <i class='subheader-icon fal fa-table'></i> <%= @livro.model_name.human %>/Incluir
    <% end %> 
    <%= render 'form' , livro: @livro %>
  </div>

app/views/livros/show.html.erb
<%- model_class = Livro -%>
<div class="wrapper wrapper-content animated fadeInRight">
   <% content_for(:title, "#{@livro.model_name.human}") %>
  <% content_for(:category_1, 'Cadastros') %>

  <% content_for :heading do %>
    <i class='subheader-icon fal fa-table'></i> <%= @livro.model_name.human %>
  <% end %>

  <div class="row">
    <div class="col-xl-12">
      <div id="panel-1" class="panel">
        <div class="panel-hdr">
              <h2>
                <span class="fw-500">Dados</span>
              </h2>
              <div class="panel-toolbar">
                  <button class="btn btn-panel waves-effect waves-themed" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                  <button class="btn btn-panel waves-effect waves-themed" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                  <button class="btn btn-panel waves-effect waves-themed" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
              </div>
            </div>
           <div class="panel-container show">
                    <div class="panel-content">
                      <p>
                        <strong><%= model_class.human_attribute_name( :nome) %>:</strong>
                        <%= @livro.nome %>
                      </p>
                            <p>
                        <strong><%= model_class.human_attribute_name( :serie_id) %>:</strong>
                        <%= @livro.serie.nome %>
                      </p>
                            <p>
                        <strong><%= model_class.human_attribute_name( :volume) %>:</strong>
                        <%= @livro.volume %>
                      </p>
                          <!-- <p>
                        <strong><%= model_class.human_attribute_name( :ano_edicao) %>:</strong>
                        <%= @livro.ano_edicao %>
                         </p>-->
                    </div>

                  <div class="panel-content d-flex py-2 rounded-bottom border-faded border-left-0 border-right-0 border-bottom-0 text-muted">
              <div class="demo">
                <%= link_to "#{content_tag(:i, nil, class: '')} Editar".html_safe, edit_livro_path(@livro), class: 'btn btn-success btn-sm' %>
                <%= link_to "#{content_tag(:i, nil, class: '')} Incluir".html_safe, new_livro_path, class: 'btn btn-primary btn-sm' %>
                <%= link_to "#{content_tag(:i, nil, class: '')} Voltar".html_safe, livros_path, class: 'btn btn-secondary btn-sm' %>
             </div>
           </div>
        </div>
      </div>
    </div>
  </div>
</div>